In [1]:
import tensorflow as tf
import numpy as np
s = tf.Session()
sr = s.run

In [2]:
x_vals = np.array([1.,3.,5.,7.,9.])
x_data = tf.placeholder(tf.float32,name='x_data')
m_const = tf.constant(3.,name='m_const')
my_product = tf.multiply(x_data,m_const,name='my_product')
for x_val in x_vals:
    print(sr(my_product,feed_dict={x_data:x_val}))
writer = tf.summary.FileWriter("C:/Users/BFD-725/Anaconda3/Lib/site-packages/tensorboard/log",tf.get_default_graph())
writer.close()

3.0
9.0
15.0
21.0
27.0


In [3]:
my_array = np.array([[1., 3., 5., 7., 9.],
[-2., 0., 2., 4., 6.],
[-6., -3., 0., 3., 6.]])
x_vals = np.array([my_array, my_array + 1])
x_data = tf.placeholder(tf.float32, shape=(3, 5),name="x_data")

In [4]:
m1 = tf.constant([[1.],[0.],[-1.],[2.],[4.]],name='m1')
m2 = tf.constant([[2.]],name='m2')
a1 = tf.constant([[10.]],name='a1')

In [5]:
prod1 = tf.matmul(x_data, m1,name='prod1')
prod2 = tf.matmul(prod1, m2,name='prod2')
add1 = tf.add(prod2, a1,name='add1')

In [7]:
writer = tf.summary.FileWriter("C:/Users/BFD-725/Anaconda3/Lib/site-packages/tensorboard/log",tf.get_default_graph())
writer.close()

In [8]:
for x_val in x_vals:
    print(s.run(add1, feed_dict={x_data: x_val}))

[[ 102.]
 [  66.]
 [  58.]]
[[ 114.]
 [  78.]
 [  70.]]


In [13]:
tf.placeholder(tf.float32, shape=(3,None))

<tf.Tensor 'Placeholder:0' shape=(3, ?) dtype=float32>

In [19]:
x_shape = [1,4,4,1]
x_val = np.random.uniform(size=x_shape)
x_data = tf.placeholder(tf.float32,shape=x_shape)
x_val

array([[[[ 0.87417995],
         [ 0.47771542],
         [ 0.59551458],
         [ 0.02190165]],

        [[ 0.10113034],
         [ 0.98364718],
         [ 0.09391962],
         [ 0.54701781]],

        [[ 0.20338663],
         [ 0.82823084],
         [ 0.476467  ],
         [ 0.41890561]],

        [[ 0.19885576],
         [ 0.01082537],
         [ 0.04901783],
         [ 0.58554896]]]])

In [20]:
my_filter = tf.constant(0.25,shape=[2,2,1,1])
my_stride = [1,2,2,1]
sr(my_filter)

array([[[[ 0.25]],

        [[ 0.25]]],


       [[[ 0.25]],

        [[ 0.25]]]], dtype=float32)

In [22]:
mov_avg_layer = tf.nn.conv2d(x_data,my_filter,my_stride,padding="SAME",name = "mov_avg_layer")
mov_avg_layer

<tf.Tensor 'mov_avg_layer_1:0' shape=(1, 2, 2, 1) dtype=float32>

In [24]:
def custom_layer(input_mat):
    ims = tf.squeeze(input_mat)
    A = tf.constant([[1., 2.], [-1., 3.]])
    b = tf.constant(1., shape=[2, 2])
    t1 = tf.matmul(A,ims)
    t2 = tf.add(t1,b)
    return(tf.sigmoid(t2))

In [26]:
with tf.name_scope("Custom_Layer") as  scope:
    custom_layer1 = custom_layer(mov_avg_layer)

In [28]:
writer = tf.summary.FileWriter("C:/Users/BFD-725/Anaconda3/Lib/site-packages/tensorboard/log",tf.get_default_graph())
writer.close()

In [27]:
sr(custom_layer1,feed_dict={x_data:x_val})

array([[ 0.90289533,  0.8889004 ],
       [ 0.789482  ,  0.86210281]], dtype=float32)