In [13]:
import tensorflow as t

In [4]:
s = t.Session()

#简单操作

In [8]:
s.run(t.range(6,12,1))

array([ 6,  7,  8,  9, 10, 11], dtype=int32)

In [10]:
s.run(t.constant(43,shape=[10,10]))

array([[43, 43, 43, 43, 43, 43, 43, 43, 43, 43],
       [43, 43, 43, 43, 43, 43, 43, 43, 43, 43],
       [43, 43, 43, 43, 43, 43, 43, 43, 43, 43],
       [43, 43, 43, 43, 43, 43, 43, 43, 43, 43],
       [43, 43, 43, 43, 43, 43, 43, 43, 43, 43],
       [43, 43, 43, 43, 43, 43, 43, 43, 43, 43],
       [43, 43, 43, 43, 43, 43, 43, 43, 43, 43],
       [43, 43, 43, 43, 43, 43, 43, 43, 43, 43],
       [43, 43, 43, 43, 43, 43, 43, 43, 43, 43],
       [43, 43, 43, 43, 43, 43, 43, 43, 43, 43]], dtype=int32)

In [11]:
s.run(t.random_uniform([3,3],1,10))

array([[ 8.4563694 ,  3.5618434 ,  2.5368104 ],
       [ 8.41355515,  3.97321463,  2.20349646],
       [ 8.76438236,  3.54928398,  9.08544064]], dtype=float32)

In [12]:
s.run(t.random_normal([3,3,3]))

array([[[ 1.04461789,  0.54661566,  2.3753171 ],
        [-0.62720132, -0.35723543,  0.24301647],
        [ 0.34628698, -0.5599156 ,  0.81172109]],

       [[ 1.64524746, -0.01394548, -1.86012554],
        [ 0.60850012, -0.20055635, -2.12585044],
        [-0.53699821, -0.22651285,  0.70698786]],

       [[-0.03551011,  1.14031279,  0.55292928],
        [ 0.39075714,  0.43021458, -0.86167401],
        [ 2.05690718,  0.3653785 , -0.51670897]]], dtype=float32)

In [15]:
c = t.constant([1,2,3,4,5,6],shape=[2,3])

In [17]:
s.run(t.random_shuffle(c))

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [19]:
t.Variable(c)

<tf.Variable 'Variable_1:0' shape=(2, 3) dtype=int32_ref>

In [26]:
import numpy as np
a = np.random.rand(3,3)

In [27]:
at = t.convert_to_tensor(a)

In [28]:
s.run(at)

array([[ 0.77426583,  0.03027706,  0.67243457],
       [ 0.13412692,  0.65883704,  0.93064221],
       [ 0.54680291,  0.2532451 ,  0.71730735]])

In [34]:
v1 = t.Variable(at,name="at")
init_op = t.global_variables_initializer()
s.run(init_op)
s.run(v1)

array([[ 0.77426583,  0.03027706,  0.67243457],
       [ 0.13412692,  0.65883704,  0.93064221],
       [ 0.54680291,  0.2532451 ,  0.71730735]])

In [35]:
x = t.placeholder(t.float32,[2,2])
y = t.identity(x-1)
x_vals = np.random.rand(2,2)

In [36]:
s.run(y,feed_dict={x:x_vals})

array([[-0.37518865, -0.75492769],
       [-0.54547232, -0.14321005]], dtype=float32)

In [41]:
v2 = t.Variable(v1)
s.run(v2.initializer)
s.run(v2)

array([[ 0.77426583,  0.03027706,  0.67243457],
       [ 0.13412692,  0.65883704,  0.93064221],
       [ 0.54680291,  0.2532451 ,  0.71730735]])

In [43]:
identity_matrix = t.diag([1.0, 1.0, 1.0])
A = t.truncated_normal([2, 3])
B = t.fill([2,3], 5.0)
C = t.random_uniform([3,2])
D = t.convert_to_tensor(np.array([[1., 2., 3.],[-3., -7.,
-1.],[0., 5., -2.]]))
print(s.run(identity_matrix))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [44]:
s.run(A+B)

array([[ 4.0106554 ,  5.19192028,  6.30671024],
       [ 5.19400501,  4.91962242,  6.19328499]], dtype=float32)

In [46]:
s.run(t.matmul(B,identity_matrix*2))

array([[ 10.,  10.,  10.],
       [ 10.,  10.,  10.]], dtype=float32)

In [48]:
s.run(t.matrix_determinant(D))

-38.0

In [50]:
s.run(t.matrix_inverse(D))

array([[-0.5       , -0.5       , -0.5       ],
       [ 0.15789474,  0.05263158,  0.21052632],
       [ 0.39473684,  0.13157895,  0.02631579]])

In [51]:
s.run(t.self_adjoint_eig(D))

(array([-10.65907521,  -0.22750691,   2.88658212]),
 array([[ 0.21749542,  0.63250104, -0.74339638],
        [ 0.84526515,  0.2587998 ,  0.46749277],
        [-0.4880805 ,  0.73004459,  0.47834331]]))

In [52]:
s.run(t.div(3,4))

0

In [54]:
sr = s.run

In [55]:
sr(t.truediv(3,4))

0.75

In [56]:
sr(t.floordiv(3.0,4.0))

0.0

In [57]:
sr(t.mod(22.0,3))

1.0

In [60]:
sr(t.cross([1.0,0.,0.],[0.,1.,0.]))

array([ 0.,  0.,  1.], dtype=float32)

In [61]:
sr(t.cross([1.0,2.,3.],[4.,1.,2.]))

array([  1.,  10.,  -7.], dtype=float32)

In [63]:
t.rsqrt

<function tensorflow.python.ops.gen_math_ops.rsqrt>

In [65]:
def custom_polynomial(value):
    return(t.subtract(3 * t.square(value), value) + 10)
print(s.run(custom_polynomial(11)))

362


In [66]:
s.run(t.nn.relu([-3,0,3]))

array([0, 0, 3], dtype=int32)

In [68]:
s.run(t.nn.relu6([-3,0,3]))

array([0, 0, 3], dtype=int32)

In [70]:
s.run(t.nn.sigmoid([1.0,2.0,3]))

array([ 0.7310586 ,  0.88079703,  0.95257413], dtype=float32)

In [72]:
s.run(t.nn.tanh([1.0,2.0,3]))

array([ 0.76159418,  0.96402758,  0.99505472], dtype=float32)

In [74]:
s.run(t.nn.softsign([1.0,2.0,3]))

array([ 0.5       ,  0.66666669,  0.75      ], dtype=float32)

In [75]:
s.run(t.nn.softplus([1.0,2.0,3]))

array([ 1.31326163,  2.12692809,  3.04858732], dtype=float32)

In [78]:
s.run(t.nn.elu(np.array([-1,0,1],dtype=float)))

array([-0.63212056,  0.        ,  1.        ])

In [85]:
from sklearn import datasets
iris = datasets.load_iris()
print(len(iris.data),iris.data[1:20])

150 [[ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]]


In [88]:
print(len(iris.target),iris.target[0])

150 0


In [89]:
set(iris.target)

{0, 1, 2}

In [90]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting MNIST_data/train-images-idx3-ubyte.gz


Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting MNIST_data/train-labels-idx1-ubyte.gz


Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz


Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [96]:
print(len(mnist.train.images),len(mnist.test.images),len(mnist.validation.images))

55000 10000 5000


In [101]:
mnist.train.labels[1,:]

array([ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.])

In [104]:
type(mnist.train)

tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet